# -*- coding: utf-8 -*-
"""Hello_World_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u5CyPzABSuLDhbszqPZHhG5AfqhMcy_A
"""

print("Hello, World!")

stg = "Hello, World!"
stg

print(stg)